Package

In [ ]:
import torch
import torchvision
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import torch.nn as nn
import torch.nn.functional as F
from torchvision.datasets import MNIST
from torchvision.transforms import ToTensor
from torchvision.utils import make_grid
from torch.utils.data.dataloader import DataLoader
from torch.utils.data import random_split
import pandas as pd

In [ ]:
import pandas as pd
import pandas as pd
import numpy as np
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
import torch
from torch import nn
from torch.nn import functional as F
from torchmetrics import Accuracy
import numpy as np
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from sklearn import preprocessing
from enum import Enum 
import pandas as pd
import copy
from pytorch_lightning import LightningModule, Trainer
from torch import nn
import torch
from torch.nn import functional as F
from torchmetrics import Accuracy

ModuleNotFoundError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
pip install torchmetrics

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 419 kB 9.3 MB/s 


In [ ]:
import matplotlib.pyplot as plt

Normalization

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/code/python/projects/ADL/ADL_(IM5062)/111ntu-homework1/training_data.csv")

In [ ]:
df

AMB_TEMP  CH4    CO  NMHC    NO   NO2   NOx   PM10  PM2.5    RH  SO2
0         16.0  2.0  0.53  0.18 -0.30  16.0  16.0  106.0  105.4  77.0  2.6
1         16.0  2.0  0.56  0.19  0.00  23.0  23.0  106.0   97.6  77.0  3.8
2         16.0  2.0  0.56  0.20  0.10  23.0  23.0  107.0   97.6  79.0  3.6
3         16.0  2.1  0.61  0.22  1.72  19.2  20.9  108.0   98.9  80.0  3.7
4         16.0  2.1  0.67  0.19 -0.40  19.0  18.0  105.0  110.6  80.0  3.6
...        ...  ...   ...   ...   ...   ...   ...    ...    ...   ...  ...
8779      20.0  1.9  0.30  0.09  1.30  12.0  13.0   63.0   23.5  86.0  1.7
8780      20.0  1.9  0.28  0.09  1.40  13.0  14.0   55.0   26.1  87.0  1.6
8781      20.0  2.0  0.33  0.11  1.30  14.0  16.0   50.0   28.7  89.0  1.5
8782      19.0  2.0  0.37  0.12  1.30  19.0  20.0   52.0   19.6  89.0  1.6
8783      19.0  2.0  0.40  0.16  1.80  23.0  25.0   54.0   11.8  90.0  1.8

[8784 rows x 11 columns]

In [ ]:
train_y = df['PM2.5']

In [ ]:
train_y

0       105.4
1        97.6
2        97.6
3        98.9
4       110.6
        ...  
8779     23.5
8780     26.1
8781     28.7
8782     19.6
8783     11.8
Name: PM2.5, Length: 8784, dtype: float64

In [ ]:
del df['PM2.5']

In [ ]:
df['AMB_TEMP'].mean()

25.256894353369763

AMB_TEMP     5.437083
CH4          0.169114
CO           0.173651
NMHC         0.160766
NO           4.094463
NO2          7.410589
NOx          9.864936
PM10        29.673641
RH          10.321507
SO2          1.415210
dtype: float64

In [ ]:
normalized_dt=(df-df.mean())/df.std()

In [ ]:
normalized_dt

AMB_TEMP       CH4        CO      NMHC        NO       NO2       NOx  \
0    -1.702548  1.158508  0.975579  0.063109 -0.736558  0.502490  0.102198   
1    -1.702548  1.158508  1.148339  0.125311 -0.663289  1.447084  0.811782   
2    -1.702548  1.158508  1.148339  0.187513 -0.638865  1.447084  0.811782   
3    -1.702548  1.749826  1.436273  0.311917 -0.243209  0.934305  0.598907   
4    -1.702548  1.749826  1.781794  0.125311 -0.760982  0.907316  0.304936   
...        ...       ...       ...       ...       ...       ...       ...   
8779 -0.966859  0.567191 -0.348917 -0.496711 -0.345787 -0.037278 -0.201909   
8780 -0.966859  0.567191 -0.464090 -0.496711 -0.321363  0.097664 -0.100540   
8781 -0.966859  1.158508 -0.176156 -0.372306 -0.345787  0.232606  0.102198   
8782 -1.150782  1.158508  0.054191 -0.310104 -0.345787  0.907316  0.507675   
8783 -1.150782  1.158508  0.226951 -0.061296 -0.223671  1.447084  1.014520   

          PM10        RH       SO2  
0     1.791526  0.078993 -0.162208  
1     1.791526  0.078993  0.685723  
2     1.825226  0.272763  0.544401  
3     1.858926  0.369648  0.615062  
4     1.757826  0.369648  0.544401  
...        ...       ...       ...  
8779  0.342429  0.950958 -0.798156  
8780  0.072829  1.047844 -0.868817  
8781 -0.095671  1.241614 -0.939478  
8782 -0.028271  1.241614 -0.868817  
8783  0.039129  1.338499 -0.727495  

[8784 rows x 10 columns]

In [ ]:
# determine the supported device
def get_device():
    if torch.cuda.is_available():
        device = torch.device('cuda:0')
    else:
        device = torch.device('cpu') # don't have GPU 
    return device

# convert a df to tensor to be used in pytorch
def df_to_tensor(df):
    device = get_device()
    return torch.from_numpy(df.values).float().to(device)

dt_tensor = df_to_tensor(normalized_dt)
training_label = df_to_tensor(train_y)
#

In [ ]:
dt_tensor

tensor([[-1.7025,  1.1585,  0.9756,  ...,  1.7915,  0.0790, -0.1622],
        [-1.7025,  1.1585,  1.1483,  ...,  1.7915,  0.0790,  0.6857],
        [-1.7025,  1.1585,  1.1483,  ...,  1.8252,  0.2728,  0.5444],
        ...,
        [-0.9669,  1.1585, -0.1762,  ..., -0.0957,  1.2416, -0.9395],
        [-1.1508,  1.1585,  0.0542,  ..., -0.0283,  1.2416, -0.8688],
        [-1.1508,  1.1585,  0.2270,  ...,  0.0391,  1.3385, -0.7275]])

In [ ]:
training_label 

tensor([105.4000,  97.6000,  97.6000,  ...,  28.7000,  19.6000,  11.8000])

In [ ]:
len(dt_tensor)

8784

In [ ]:
from torch.utils.data import random_split

train_ds, val_ds = random_split(dt_tensor, [7320, 1464])
len(train_ds), len(val_ds)

(7320, 1464)

In [ ]:
train_ds[0]

tensor([-0.0472, -0.0241,  0.2270, -0.3101, -0.6144, -0.3072, -0.5060,  0.5446,
        -0.3085,  0.7564])

In [ ]:
val_ds[0]

tensor([-0.5990, -0.6154, -0.3489, -0.7455, -0.5900, -0.8199, -0.8709, -0.0957,
        -3.3120, -0.5862])

In [ ]:
from torch.utils.data import DataLoader

batch_size = 61

train_loader = DataLoader(train_ds, batch_size, shuffle=True, num_workers=4, pin_memory=True)
val_loader = DataLoader(val_ds, batch_size*2, num_workers=4, pin_memory=True)

/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:566: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))


In [ ]:
class CustomStarDataset(Dataset):
    # This loads the data and converts it, make data rdy
    def __init__(self):
        # load data
        self.df=pd.read_csv("/content/drive/MyDrive/code/python/projects/ADL/ADL_(IM5062)/111ntu-homework1/training_data.csv")
        # extract labels
        self.df_labels=df[['PM2.5']]
        # drop non numeric columns to make tutorial simpler, in real life do categorical encoding
        self.df=df.drop(columns=['PM2.5'])
        # normalized
        self.df = (self.df -self.df.mean())/self.df.std()

        # conver to torch dtypes
        self.dataset=torch.tensor(self.df.to_numpy()).float()

        self.labels=torch.tensor(self.df_labels.to_numpy().reshape(-1)).long()
    
    # This returns the total amount of samples in your Dataset
    def __len__(self):
        return len(self.dataset)
    
    # This returns given an index the i-th sample and label
    def __getitem__(self, idx):
        return self.dataset[idx],self.labels[idx]

In [ ]:
ds=CustomStarDataset()
ds

In [ ]:
# what can it do?
# for now only return the ith sample and label
for i in range(min(5,ds.__len__())):
    # access our ith sample
    print(ds[i])

(tensor([-1.7025,  1.1585,  0.9756,  0.0631, -0.7366,  0.5025,  0.1022,  1.7915,
         0.0790, -0.1622]), tensor(105))
(tensor([-1.7025,  1.1585,  1.1483,  0.1253, -0.6633,  1.4471,  0.8118,  1.7915,
         0.0790,  0.6857]), tensor(97))
(tensor([-1.7025,  1.1585,  1.1483,  0.1875, -0.6389,  1.4471,  0.8118,  1.8252,
         0.2728,  0.5444]), tensor(97))
(tensor([-1.7025,  1.7498,  1.4363,  0.3119, -0.2432,  0.9343,  0.5989,  1.8589,
         0.3696,  0.6151]), tensor(98))
(tensor([-1.7025,  1.7498,  1.7818,  0.1253, -0.7610,  0.9073,  0.3049,  1.7578,
         0.3696,  0.5444]), tensor(110))


In [ ]:
# create a dataloader
dl=DataLoader(ds,batch_size=24, num_workers=2, shuffle=True,drop_last=True)

In [ ]:
# use dataloader
counter=0
for epoch in [1,2,3]:
    for batch,label in dl:
        if counter==0:
            print(batch,label)
            counter+=1
        print(batch.size(),label.size())

tensor([[ 1.3667e-01, -6.1544e-01,  2.8454e-01,  2.4268e+00, -4.4348e-01,
         -1.7222e-01, -4.0465e-01, -6.6857e-01,  1.2416e+00, -5.1551e-01],
        [ 3.2060e-01, -6.1544e-01,  1.6090e+00,  9.3394e-01, -5.1675e-01,
          2.3261e-01,  8.2893e-04, -1.9677e-01,  2.7276e-01, -2.3287e-01],
        [ 3.2060e-01, -2.4127e-02, -7.5202e-01, -1.8570e-01,  3.6249e-01,
         -4.2861e-01, -2.0191e-01, -9.7187e-01,  6.6030e-01,  2.6176e-01],
        [-1.7025e+00,  1.1585e+00,  5.1488e-01,  9.0641e-04,  1.4127e+00,
          1.4471e+00,  1.7241e+00, -1.0056e+00,  1.0478e+00, -5.8617e-01],
        [ 1.3667e-01, -6.1544e-01, -1.0975e+00,  9.0641e-04, -4.4348e-01,
         -7.9295e-01, -7.8985e-01, -1.0730e+00,  1.2416e+00, -1.2928e+00],
        [-4.1509e-01,  1.7498e+00,  6.8765e-01, -3.1010e-01,  1.7790e+00,
         -1.7222e-01,  6.0904e-01,  9.4903e-01,  1.2416e+00, -5.1551e-01],
        [ 8.7236e-01, -1.2068e+00,  3.4212e-01,  9.3394e-01,  1.4268e-01,
          3.6755e-01,  3.0494e-0

Build model

In [ ]:
input_size = 10

hidden_size1 = 64 # you can change this
hidden_size2 = 32
hidden_size3 = 16

num_classes = 10
# hidden layer1
linear1 = nn.Linear(input_size, hidden_size1)
# hidden layer2
linear2 = nn.Linear(hidden_size1, hidden_size2)
# hidden layer3
linear3 = nn.Linear(hidden_size2, hidden_size3)
# output layer
#

for batch in train_loader:
  print(batch.size())
  # layer1
  out = linear1(batch)
# Apply activation function
#


torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([61, 10])
torch.Size([6

In [ ]:

print(out)
print(out.size())

tensor([[ 0.4504,  0.1932,  0.0020,  ..., -0.8007, -0.4227,  0.2406],
        [-0.1785,  0.3188,  0.6996,  ...,  0.2636, -0.9227,  0.5260],
        [-1.4317, -0.4384,  0.8963,  ...,  0.3109, -1.0170, -0.9128],
        ...,
        [-0.8213,  0.6035,  1.3085,  ..., -0.0690, -0.0451, -0.0239],
        [-0.0558,  0.3268, -0.8785,  ..., -0.1327,  0.6795, -0.5487],
        [-0.3673,  0.0974,  0.9443,  ...,  1.1402, -0.8526,  0.5661]],
       grad_fn=<AddmmBackward0>)
torch.Size([61, 64])


In [ ]:
def fit(epochs, lr, model, train_loader, val_loader, opt_func=torch.optim.SGD):
    """Train the model using gradient descent"""
    history = []
    optimizer = opt_func(model.parameters(), lr)
    for epoch in range(epochs):
        # Training Phase 
        for batch in train_loader:
            loss = model.training_step(batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
        # Validation phase
        result = evaluate(model, val_loader)
        model.epoch_end(epoch, result)
        history.append(result)
    return history


In [ ]:
class MnistModel_2(nn.Module):
    """Feedfoward neural network with  hidden layer"""
    def __init__(self, in_size, hidden_size1, hidden_size2, hidden_size3, out_size):
        super().__init__()
        # hidden layer1
        self.linear1 = nn.Linear(in_size, hidden_size1)
        # hidden layer2
        self.linear2 = nn.Linear(hidden_size1, hidden_size2)
        # hidden layer3
        self.linear3 = nn.Linear(hidden_size2, hidden_size3)
        # output layer
        self.linear_output = nn.Linear(hidden_size3, out_size)
        
    def forward(self, xb):
        # Flatten the image tensors
        xb = xb.view(xb.size(0), -1)

        # layer1
        # Get intermediate outputs using hidden layer
        out = self.linear1(xb)
        # Apply activation function
        out = F.relu(out)

        # layer2
        # Get intermediate outputs using hidden layer
        out = self.linear2(out)
        # Apply activation function
        out = F.relu(out)

        # layer3
        # Get intermediate outputs using hidden layer
        out = self.linear3(out)
        # Apply activation function
        out = F.relu(out)


        # Get predictions using output layer
        out = self.linear_output(out)
        return out
    
    def training_step(self, batch):
        data, labels = batch 
        out = self(data)                  # Generate predictions
        loss = F.cross_entropy(out, labels) # Calculate loss
        return loss
    
    def validation_step(self, batch):
        data, labels = batch 
        out = self(data)                    # Generate predictions
        loss = F.cross_entropy(out, labels)   # Calculate loss
        acc = accuracy(out, labels)           # Calculate accuracy
        return {'val_loss': loss, 'val_acc': acc}
        
    def validation_epoch_end(self, outputs):
        batch_losses = [x['val_loss'] for x in outputs]
        epoch_loss = torch.stack(batch_losses).mean()   # Combine losses
        batch_accs = [x['val_acc'] for x in outputs]
        epoch_acc = torch.stack(batch_accs).mean()      # Combine accuracies
        return {'val_loss': epoch_loss.item(), 'val_acc': epoch_acc.item()}
    
    def epoch_end(self, epoch, result):
        print("Epoch [{}], val_loss: {:.4f}, val_acc: {:.4f}".format(epoch, result['val_loss'], result['val_acc']))

In [ ]:
def accuracy(outputs, labels):
    _, preds = torch.max(outputs, dim=1)
    return torch.tensor(torch.sum(preds == labels).item() / len(preds))

In [ ]:
input_size = 10

hidden_size1 = 64 # you can change this
hidden_size2 = 32
hidden_size3 = 16

num_classes = 10

Fit dataset

In [ ]:
model_2 = MnistModel_2(input_size, hidden_size1 = 64, hidden_size2 = 32, hidden_size3 = 16, out_size=num_classes)

In [ ]:
for images, labels in train_loader:
    outputs = model_2(images)
    loss = F.cross_entropy(outputs, labels)
    print('Loss:', loss.item())
    break

print('outputs.shape : ', outputs.shape)
print('Sample outputs :\n', outputs[:2].data)

In [ ]:
for t in model_2.parameters():
    print(t.shape)

In [ ]:
for images, labels in train_loader:
    outputs = model_2(images)
    loss = F.cross_entropy(outputs, labels)
    print('Loss:', loss.item())
    break

print('outputs.shape : ', outputs.shape)
print('Sample outputs :\n', outputs[:2].data)

In [ ]:
def get_default_device():
    """Pick GPU if available, else CPU"""
    if torch.cuda.is_available():
        return torch.device('cuda')
    else:
        return torch.device('cpu')

In [ ]:
def to_device(data, device):
    """Move tensor(s) to chosen device"""
    if isinstance(data, (list,tuple)):
        return [to_device(x, device) for x in data]
    return data.to(device, non_blocking=True)

In [ ]:
for images, labels in train_loader:
    print(images.shape)
    images = to_device(images, device)
    print(images.device)
    break

In [ ]:
class DeviceDataLoader():
    """Wrap a dataloader to move data to a device"""
    def __init__(self, dl, device):
        self.dl = dl
        self.device = device
        
    def __iter__(self):
        """Yield a batch of data after moving it to device"""
        for b in self.dl: 
            yield to_device(b, self.device)

    def __len__(self):
        """Number of batches"""
        return len(self.dl)

In [ ]:
train_loader = DeviceDataLoader(train_loader, device)
val_loader = DeviceDataLoader(val_loader, device)

In [ ]:
def evaluate(model, val_loader):
    """Evaluate the model's performance on the validation set"""
    outputs = [model.validation_step(batch) for batch in val_loader]
    return model.validation_epoch_end(outputs)

def fit(epochs, lr, model, train_loader, val_loader, opt_func=torch.optim.SGD):
    """Train the model using gradient descent"""
    history = []
    optimizer = opt_func(model.parameters(), lr)
    for epoch in range(epochs):
        # Training Phase 
        for batch in train_loader:
            loss = model.training_step(batch)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
        # Validation phase
        result = evaluate(model, val_loader)
        model.epoch_end(epoch, result)
        history.append(result)
    return history

In [ ]:
# Model (on GPU)
model_2 = MnistModel_2(input_size, hidden_size1 = 64, hidden_size2 = 32, hidden_size3 = 16, out_size=num_classes)
to_device(model_2, device)

In [ ]:
history = [evaluate(model_2, val_loader)]
history

In [ ]:
history += fit(5, 0.5, model_2, train_loader, val_loader)

Re-load best weight, and prediction test dataset

save test prediction, and plot figure

Upload Format