# import


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import statsmodels.api as sm
from pandas import DataFrame , concat
from sklearn.metrics import mean_absolute_error , mean_squared_error
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
from numpy import mean , concatenate
from math import sqrt
from pandas import read_csv
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Activation
from numpy import array , hstack
from tensorflow import keras
import tensorflow as tf
import seaborn as sns
import torch
sns.set()

# data process

In [ ]:
training_x = np.load('/content/drive/MyDrive/code/python/projects/ADL/ADL_(IM5062)/111ntu-homework3/training_x.npy')

In [ ]:
training_x

array([[14.33333333,  0.33333333,  7.66666667, ...,  2.        ,
         0.        ,  0.33333333],
       [14.        ,  0.33333333,  9.33333333, ...,  2.        ,
        -0.33333333,  0.33333333],
       [14.        ,  0.33333333,  5.66666667, ...,  2.        ,
         0.        ,  0.66666667],
       ...,
       [16.        ,  0.        ,  2.        , ...,  1.        ,
         0.        ,  3.        ],
       [16.        ,  0.        ,  1.        , ...,  2.        ,
         0.66666667,  4.66666667],
       [15.        ,  0.        ,  0.66666667, ...,  2.        ,
         1.33333333,  4.33333333]])

In [ ]:
training_x.shape[0]

8760

In [ ]:
training_y = np.load('/content/drive/MyDrive/code/python/projects/ADL/ADL_(IM5062)/111ntu-homework3/training_y.npy')

In [ ]:
training_y

array([[34.],
       [37.],
       [35.],
       ...,
       [30.],
       [49.],
       [74.]])

In [ ]:
# create an Empty DataFrame object
df = pd.DataFrame(index=range(training_x.shape[0]),columns=range(14))
  
print(df)

       0    1    2    3    4    5    6    7    8    9    10   11   12   13
0     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
8755  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8756  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8757  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8758  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8759  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[8760 rows x 14 columns]


In [ ]:
df.iloc[0,0] = 0
df.iloc[1,0] = 1
df.iloc[0,1] = 2
df.iloc[1,1] = 3

In [ ]:
df

0    1    2    3    4    5    6    7    8    9    10   11   12   13
0       0    2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1       1    3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
8755  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8756  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8757  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8758  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8759  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[8760 rows x 14 columns]

In [ ]:
for i in range(training_x.shape[0]):
  for j in range(13):
    df.iloc[i,j] = training_x[i][j]
  df.iloc[i,13] = training_y[i][0]


In [ ]:
df = df.rename({0: 'AMB_TEMP', 1: 'CO',2: 'NO',3: 'NO2',4: 'NOx',5: 'O3',6: 'PM10',7: 'RAINFALL',8: 'RH',9: 'SO2',10: 'THC',11: 'cos_wind',12: 'sin_wind',13: 'PM2.5',}, axis='columns')

In [ ]:
df 

AMB_TEMP        CO         NO        NO2        NOx         O3  \
0     14.333333  0.333333   7.666667       37.0  44.666667  12.333333   
1          14.0  0.333333   9.333333  34.333333  43.666667  14.333333   
2          14.0  0.333333   5.666667  36.666667  42.333333  14.666667   
3     13.666667  0.666667  16.666667  37.333333  54.333333  12.333333   
4     13.333333  0.333333   6.333333  24.333333  30.666667  21.333333   
...         ...       ...        ...        ...        ...        ...   
8755       16.0  0.333333        4.0  38.666667       43.0  23.666667   
8756       16.0       0.0   2.333333  33.333333  36.666667  27.333333   
8757       16.0       0.0        2.0  29.333333  31.666667  32.666667   
8758       16.0       0.0        1.0       22.0  23.333333  39.666667   
8759       15.0       0.0   0.666667  14.666667       16.0  41.333333   

           PM10 RAINFALL         RH       SO2  THC  cos_wind  sin_wind PM2.5  
0          53.0      0.0  76.333333  1.666667  2.0       0.0  0.333333  34.0  
1     53.666667      0.0       78.0  4.666667  2.0 -0.333333  0.333333  37.0  
2          55.0      0.0  77.333333       4.0  2.0       0.0  0.666667  35.0  
3     57.333333      0.0  78.666667       3.0  2.0 -0.333333  0.333333  32.0  
4     54.333333      0.0  80.333333       2.0  2.0  0.333333  0.666667  31.0  
...         ...      ...        ...       ...  ...       ...       ...   ...  
8755  55.333333      0.0  61.666667  1.666667  1.0       0.0       2.0  31.0  
8756  54.666667      0.0  62.333333  1.333333  1.0       0.0  2.333333  28.0  
8757  55.333333      0.0  61.666667  2.333333  1.0       0.0       3.0  30.0  
8758  86.333333      0.0  63.666667  6.666667  2.0  0.666667  4.666667  49.0  
8759      134.0      0.0       64.0       9.0  2.0  1.333333  4.333333  74.0  

[8760 rows x 14 columns]

In [ ]:
df1 = df.T

In [ ]:
df1

0          1          2          3          4          5     \
AMB_TEMP  14.333333       14.0       14.0  13.666667  13.333333  13.333333   
CO         0.333333   0.333333   0.333333   0.666667   0.333333   0.333333   
NO         7.666667   9.333333   5.666667  16.666667   6.333333       12.0   
NO2            37.0  34.333333  36.666667  37.333333  24.333333  24.666667   
NOx       44.666667  43.666667  42.333333  54.333333  30.666667  37.333333   
O3        12.333333  14.333333  14.666667  12.333333  21.333333       22.0   
PM10           53.0  53.666667       55.0  57.333333  54.333333  49.666667   
RAINFALL        0.0        0.0        0.0        0.0        0.0        0.0   
RH        76.333333       78.0  77.333333  78.666667  80.333333       81.0   
SO2        1.666667   4.666667        4.0        3.0        2.0   2.666667   
THC             2.0        2.0        2.0        2.0        2.0        2.0   
cos_wind        0.0  -0.333333        0.0  -0.333333   0.333333        0.0   
sin_wind   0.333333   0.333333   0.666667   0.333333   0.666667   0.666667   
PM2.5          34.0       37.0       35.0       32.0       31.0       29.0   

               6          7          8          9     ...       8750  \
AMB_TEMP  13.333333  13.666667       15.0  17.666667  ...  20.333333   
CO         0.333333   0.333333   0.666667   0.333333  ...        0.0   
NO             28.0  22.666667  15.333333  12.333333  ...        2.0   
NO2       27.666667       30.0  34.333333  34.333333  ...       10.0   
NOx       55.666667       53.0       50.0  47.333333  ...  12.666667   
O3             21.0  18.666667  18.666667  28.666667  ...  51.666667   
PM10      49.333333  53.333333  57.333333       62.0  ...       48.0   
RAINFALL        0.0        0.0        0.0        0.0  ...        0.0   
RH        81.666667  80.666667       76.0  65.666667  ...  53.333333   
SO2        6.666667        8.0        6.0   4.666667  ...   1.666667   
THC             2.0        2.0        2.0        2.0  ...        1.0   
cos_wind  -0.333333  -0.333333  -0.333333   0.333333  ...        0.0   
sin_wind   0.333333   0.333333   1.333333   2.666667  ...   2.666667   
PM2.5          29.0       37.0       38.0       34.0  ...       32.0   

               8751       8752       8753       8754       8755       8756  \
AMB_TEMP  19.666667  18.666667  17.333333       17.0       16.0       16.0   
CO              0.0        0.0        0.0        0.0   0.333333        0.0   
NO              2.0   1.666667        2.0   1.666667        4.0   2.333333   
NO2            11.0  12.333333  20.666667       26.0  38.666667  33.333333   
NOx       13.666667  14.666667  23.333333  27.666667       43.0  36.666667   
O3        52.666667  49.666667       41.0       38.0  23.666667  27.333333   
PM10      45.666667  41.333333       44.0  51.333333  55.333333  54.666667   
RAINFALL        0.0        0.0        0.0        0.0        0.0        0.0   
RH        52.666667  56.333333       61.0  62.666667  61.666667  62.333333   
SO2        1.666667   1.666667   1.666667   1.333333   1.666667   1.333333   
THC             1.0        1.0        1.0        1.0        1.0        1.0   
cos_wind        0.0        0.0        0.0        0.0        0.0        0.0   
sin_wind        3.0        2.0   2.333333   2.333333        2.0   2.333333   
PM2.5          27.0       27.0       34.0       33.0       31.0       28.0   

               8757       8758       8759  
AMB_TEMP       16.0       16.0       15.0  
CO              0.0        0.0        0.0  
NO              2.0        1.0   0.666667  
NO2       29.333333       22.0  14.666667  
NOx       31.666667  23.333333       16.0  
O3        32.666667  39.666667  41.333333  
PM10      55.333333  86.333333      134.0  
RAINFALL        0.0        0.0        0.0  
RH        61.666667  63.666667       64.0  
SO2        2.333333   6.666667        9.0  
THC             1.0        2.0        2.0  
cos_wind        0.0   0.666667   1.333333  
sin_wind        3.0 

In [ ]:
df1.iloc[13,:20]

0     34.0
1     37.0
2     35.0
3     32.0
4     31.0
5     29.0
6     29.0
7     37.0
8     38.0
9     34.0
10    33.0
11    31.0
12    30.0
13    33.0
14    37.0
15    36.0
16    33.0
17    31.0
18    30.0
19    27.0
Name: PM2.5, dtype: object

In [ ]:
data_start_date = df1.columns[1]
data_end_date = df1.columns[-1]
print('Data ranges from %s to %s' % (data_start_date, data_end_date))

Data ranges from 1 to 8759


In [ ]:
AMB_TEMP = df['AMB_TEMP']
CO = df['CO']
NO =df['NO']
NO2 = df['NO2']
NOx = df['NOx']
O3 =df['O3']
PM10 =df['PM10']
RAINFALL =df['RAINFALL']
RH =df['RH']
SO2 = df['SO2']
THC =df['THC']
cos_wind =df['cos_wind']
sin_wind = df['sin_wind']
PM2_5 = df['PM2.5']

AMB_TEMP = AMB_TEMP.values
CO = CO.values
NO =NO.values
NO2 = NO2.values
NOx = NOx.values
O3 =O3.values
PM10 =PM10.values
RAINFALL =RAINFALL.values
RH =RH.values
SO2 = SO2.values
THC =THC.values
cos_wind =cos_wind.values
sin_wind = sin_wind.values
PM2_5 = PM2_5.values


In [ ]:
plt.figure(figsize=(30, 6))
plt.plot(AMB_TEMP, label='AMB_TEMP')
plt.plot(CO , label='CO')
plt.plot(NO , label='NO')
plt.plot(NO2 , label='NO2')
plt.plot(NOx , label='NOx')
plt.plot(O3, label='O3')
plt.plot(PM10 , label='PM10')
plt.plot(RAINFALL , label='RAINFALL')
plt.plot(RH , label='RH')
plt.plot(SO2, label='SO2')
plt.plot(THC , label='THC')
plt.plot(cos_wind, label='cos_wind')
plt.plot(sin_wind, label='sin_wind')
plt.plot(PM2_5 , label='PM2.5')
plt.legend()
plt.show()

In [ ]:
AMB_TEMP = AMB_TEMP.reshape((len(AMB_TEMP), 1)).astype('float64')
CO = CO.reshape((len(CO), 1)).astype('float64')
NO =NO.reshape((len(NO), 1)).astype('float64')
NO2 = NO2.reshape((len(NO2), 1)).astype('float64')
NOx = NOx.reshape((len(NOx), 1)).astype('float64')
O3 =O3.reshape((len(O3), 1)).astype('float64')
PM10 =PM10.reshape((len(PM10), 1)).astype('float64')
RAINFALL =RAINFALL.reshape((len(RAINFALL), 1)).astype('float64')
RH =RH.reshape((len(RH), 1)).astype('float64')
SO2 = SO2.reshape((len(SO2), 1)).astype('float64')
THC =THC.reshape((len(THC), 1)).astype('float64')
cos_wind =cos_wind.reshape((len(cos_wind), 1)).astype('float64')
sin_wind = sin_wind.reshape((len(sin_wind ), 1)).astype('float64')
PM2_5 = PM2_5.reshape((len(PM2_5), 1)).astype('float64')


print(PM2_5.shape)


(8760, 1)


In [ ]:
PM2_5

array([[34.],
       [37.],
       [35.],
       ...,
       [30.],
       [49.],
       [74.]])

In [ ]:
# normalization features
scaler = MinMaxScaler(feature_range=(0, 1))

# AMB_TEMP_scaled = scaler.fit_transform(AMB_TEMP)
# CO_scaled = scaler.fit_transform(CO)
# NO_scaled =scaler.fit_transform(NO)
# NO2_scaled = scaler.fit_transform(NO2)
# NOx_scaled = scaler.fit_transform(NOx)
# O3_scaled =scaler.fit_transform(O3)
# PM10_scaled =scaler.fit_transform(PM10)
# RAINFALL_scaled =scaler.fit_transform(RAINFALL)
# RH_scaled =scaler.fit_transform(RH)
# SO2_scaled = scaler.fit_transform(SO2)
# THC_scaled =scaler.fit_transform(THC)
# cos_wind_scaled =scaler.fit_transform(cos_wind)
# sin_wind_scaled = scaler.fit_transform(sin_wind)
# PM2_5_scaled = scaler.fit_transform(PM2_5)
# horizontally stack columns
# dataset_stacked = hstack((AMB_TEMP_scaled, CO_scaled, NO_scaled, NO2_scaled, NOx_scaled, O3_scaled, PM10_scaled, RAINFALL_scaled, RH_scaled, SO2_scaled, THC_scaled ,cos_wind_scaled, sin_wind_scaled, PM2_5_scaled))
dataset_stacked = hstack((AMB_TEMP, CO, NO, NO2, NOx, O3, PM10, RAINFALL, RH, SO2, THC ,cos_wind, sin_wind, PM2_5))

print ("dataset_stacked.shape" , dataset_stacked.shape) 

dataset_stacked.shape (8760, 14)


In [ ]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps_in, n_steps_out):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps_in
		out_end_ix = end_ix + 1 + n_steps_out
		# check if we are beyond the dataset
		if out_end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix+1:out_end_ix, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [ ]:
# choose a number of time steps #change this accordingly
n_steps_in, n_steps_out = 8 , 8 

# covert into input/output
X, y = split_sequences(dataset_stacked, n_steps_in, n_steps_out)

print ("X.shape" , X.shape) 
print ("y.shape" , y.shape) 

X.shape (8744, 8, 13)
y.shape (8744, 8)


In [ ]:
X[0]

array([[14.33333333,  0.33333333,  7.66666667, 37.        , 44.66666667,
        12.33333333, 53.        ,  0.        , 76.33333333,  1.66666667,
         2.        ,  0.        ,  0.33333333],
       [14.        ,  0.33333333,  9.33333333, 34.33333333, 43.66666667,
        14.33333333, 53.66666667,  0.        , 78.        ,  4.66666667,
         2.        , -0.33333333,  0.33333333],
       [14.        ,  0.33333333,  5.66666667, 36.66666667, 42.33333333,
        14.66666667, 55.        ,  0.        , 77.33333333,  4.        ,
         2.        ,  0.        ,  0.66666667],
       [13.66666667,  0.66666667, 16.66666667, 37.33333333, 54.33333333,
        12.33333333, 57.33333333,  0.        , 78.66666667,  3.        ,
         2.        , -0.33333333,  0.33333333],
       [13.33333333,  0.33333333,  6.33333333, 24.33333333, 30.66666667,
        21.33333333, 54.33333333,  0.        , 80.33333333,  2.        ,
         2.        ,  0.33333333,  0.66666667],
       [13.33333333,  0.333333

In [ ]:
y[0]

array([34., 33., 31., 30., 33., 37., 36., 33.])

In [ ]:
split = 6996
train_X , train_y = X[:split, :] , y[:split, :]
test_X , test_y = X[split:, :] , y[split:, :]

n_features = train_X.shape[2]

In [ ]:
print ("train_X.shape" , train_X.shape) 
print ("train_y.shape" , train_y.shape) 
print ("test_X.shape" , test_X.shape) 
print ("test_y.shape" , test_y.shape) 
print ("n_features" , n_features)

train_X.shape (6996, 8, 13)
train_y.shape (6996, 8)
test_X.shape (1748, 8, 13)
test_y.shape (1748, 8)
n_features 13


In [ ]:
# train_X

In [ ]:
# train_X = torch.from_numpy(train_X)
# train_y = tf.convert_to_tensor(train_y)
# test_X = tf.convert_to_tensor(test_X)
# est_y    = tf.convert_to_tensor(est_y)


# LSTM model


In [ ]:
#optimizer learning rate
opt = keras.optimizers.Adam(learning_rate=0.05, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=1e-06)

# define model
model = Sequential()
model.add(LSTM(50, activation='relu', return_sequences=True, input_shape=(n_steps_in, n_features)))
model.add(LSTM(50, activation='relu'))
model.add(Dense(n_steps_out))
model.add(Activation('linear'))
model.compile(loss='mse' , optimizer=opt , metrics=['mse'])

In [ ]:
# Fit network
history = model.fit(train_X , train_y , epochs=10 , steps_per_epoch=50 , verbose=1 ,validation_data=(test_X, test_y) ,shuffle=False)

Epoch 1/10
50/50 [==============================] - 4s 28ms/step - loss: 1119863.1250 - mse: 1119863.1250 - val_loss: 1053.7848 - val_mse: 1053.7848
Epoch 2/10
50/50 [==============================] - 1s 19ms/step - loss: 627.5312 - mse: 627.5312 - val_loss: 286.5471 - val_mse: 286.5471
Epoch 3/10
50/50 [==============================] - 1s 19ms/step - loss: 337.4649 - mse: 337.4649 - val_loss: 239.3423 - val_mse: 239.3423
Epoch 4/10
50/50 [==============================] - 1s 19ms/step - loss: 303.7269 - mse: 303.7269 - val_loss: 214.3296 - val_mse: 214.3296
Epoch 5/10
50/50 [==============================] - 1s 23ms/step - loss: 293.7065 - mse: 293.7065 - val_loss: 207.3612 - val_mse: 207.3612
Epoch 6/10
50/50 [==============================] - 1s 24ms/step - loss: 289.5649 - mse: 289.5649 - val_loss: 203.6567 - val_mse: 203.6567
Epoch 7/10
50/50 [==============================] - 1s 22ms/step - loss: 287.3677 - mse: 287.3677 - val_loss: 202.1445 - val_mse: 202.1445
Epoch 8/10
50/50 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# testing 


In [ ]:
testing_x = np.load('/content/drive/MyDrive/code/python/projects/ADL/ADL_(IM5062)/111ntu-homework3/testing_x.npy')

In [ ]:
testing_x 

array([[15.        ,  0.        ,  0.66666667, ...,  2.        ,
         1.33333333,  3.33333333],
       [14.66666667,  0.        ,  0.66666667, ...,  2.        ,
         0.66666667,  3.33333333],
       [14.        ,  0.        ,  0.66666667, ...,  2.        ,
         1.        ,  3.        ],
       ...,
       [16.        ,  0.        ,  0.66666667, ...,  1.        ,
         0.33333333,  3.33333333],
       [16.        ,  0.        ,  1.        , ...,  1.        ,
         0.33333333,  3.        ],
       [16.        ,  0.        ,  1.        , ...,  1.        ,
         0.33333333,  4.33333333]])

In [ ]:
# create an Empty DataFrame object
df_test = pd.DataFrame(index=range(testing_x.shape[0]),columns=range(14))
  
print(df_test)

       0    1    2    3    4    5    6    7    8    9    10   11   12   13
0     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
8755  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8756  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8757  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8758  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8759  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[8760 rows x 14 columns]


In [ ]:
for i in range(testing_x.shape[0]):
  for j in range(13):
    df_test.iloc[i,j] = testing_x[i][j]
  df_test.iloc[i,13] = testing_x[i][0]


In [ ]:
df_test = df_test.rename({0: 'AMB_TEMP', 1: 'CO',2: 'NO',3: 'NO2',4: 'NOx',5: 'O3',6: 'PM10',7: 'RAINFALL',8: 'RH',9: 'SO2',10: 'THC',11: 'cos_wind',12: 'sin_wind'}, axis='columns')

In [ ]:
df_test

AMB_TEMP   CO        NO        NO2        NOx         O3        PM10  \
0          15.0  0.0  0.666667       11.0  12.666667       42.0  159.333333   
1     14.666667  0.0  0.666667       11.0  12.666667       41.0  161.333333   
2          14.0  0.0  0.666667  10.333333  12.333333       41.0  149.666667   
3          14.0  0.0  0.666667        8.0        9.0  40.333333  135.666667   
4          14.0  0.0  0.333333   7.333333   8.333333  39.666667  119.666667   
...         ...  ...       ...        ...        ...        ...         ...   
8755       16.0  0.0  1.333333  14.333333  15.666667  56.666667  114.666667   
8756       16.0  0.0  0.666667  14.666667       16.0       53.0       115.0   
8757       16.0  0.0  0.666667  12.333333  13.666667  49.333333       110.0   
8758       16.0  0.0       1.0       12.0  13.333333  45.666667  100.333333   
8759       16.0  0.0       1.0       10.0  11.333333       46.0   92.333333   

     RAINFALL         RH       SO2  THC  cos_wind  sin_wind         13  
0         0.0       64.0  8.666667  2.0  1.333333  3.333333       15.0  
1         0.0  63.666667  7.333333  2.0  0.666667  3.333333  14.666667  
2         0.0  64.333333  6.333333  2.0       1.0       3.0       14.0  
3         0.0       65.0  5.333333  1.0  0.666667       3.0       14.0  
4         0.0  65.333333  4.333333  1.0  0.666667       3.0       14.0  
...       ...        ...       ...  ...       ...       ...        ...  
8755      0.0       67.0  4.333333  1.0  0.333333  3.333333       16.0  
8756      0.0  68.666667       4.0  1.0  0.333333  3.333333       16.0  
8757      0.0  70.333333       3.0  1.0  0.333333  3.333333       16.0  
8758      0.0  72.333333       3.0  1.0  0.333333       3.0       16.0  
8759      0.0  69.666667       2.0  1.0  0.333333  4.333333       16.0  

[8760 rows x 14 columns]

In [ ]:
# read test data
AMB_TEMP_test = df_test['AMB_TEMP'].values
CO_test = df_test['CO'].values
NO_test =df_test['NO'].values
NO2_test = df_test['NO2'].values
NOx_test = df_test['NOx'].values
O3_test =df_test['O3'].values
PM10_test =df_test['PM10'].values
RAINFALL_test =df_test['RAINFALL'].values
RH_test =df_test['RH'].values
SO2_test = df_test['SO2'].values
THC_test =df_test['THC'].values
cos_wind_test =df_test['cos_wind'].values
sin_wind_test = df_test['sin_wind'].values



# convert to [rows, columns] structure
AMB_TEMP_test = AMB_TEMP_test.reshape((len(AMB_TEMP_test), 1)).astype('float64')
CO_test = CO_test.reshape((len(CO_test), 1)).astype('float64')
NO_test =NO_test.reshape((len(NO_test), 1)).astype('float64')
NO2_test = NO2_test.reshape((len(NO2_test), 1)).astype('float64')
NOx_test = NOx_test.reshape((len(NOx_test), 1)).astype('float64')
O3_test =O3_test.reshape((len(O3_test), 1)).astype('float64')
PM10_test =PM10_test.reshape((len(PM10_test), 1)).astype('float64')
RAINFALL_test =RAINFALL_test.reshape((len(RAINFALL_test), 1)).astype('float64')
RH_test =RH_test.reshape((len(RH_test), 1)).astype('float64')
SO2_test = SO2_test.reshape((len(SO2_test), 1)).astype('float64')
THC_test =THC_test.reshape((len(THC_test), 1)).astype('float64')
cos_wind_test =cos_wind_test.reshape((len(cos_wind_test), 1)).astype('float64')
sin_wind_test = sin_wind_test.reshape((len(sin_wind_test ), 1)).astype('float64')



# AMB_TEMP_test_scaled = scaler.fit_transform(AMB_TEMP_test)
# CO_test_scaled = scaler.fit_transform(CO_test)
# NO_test_scaled =scaler.fit_transform(NO_test)
# NO2_test_scaled = scaler.fit_transform(NO2_test)
# NOx_test_scaled = scaler.fit_transform(NOx_test)
# O3_test_scaled =scaler.fit_transform(O3_test)
# PM10_test_scaled =scaler.fit_transform(PM10_test)
# RAINFALL_test_scaled =scaler.fit_transform(RAINFALL_test)
# RH_test_scaled =scaler.fit_transform(RH_test)
# SO2_test_scaled = scaler.fit_transform(SO2_test)
# THC_test_scaled =scaler.fit_transform(THC_test)
# cos_wind_test_scaled =scaler.fit_transform(cos_wind_test)
# sin_wind_test_scaled = scaler.fit_transform(sin_wind_test)

In [ ]:
# def prep_data(x1_test_scaled,x2_test_scaled,x3_test_scaled,x4_test_scaled,x5_test_scaled,x6_test_scaled,
#               x7_test_scaled,x8_test_scaled,x9_test_scaled,x10_test_scaled,x11_test_scaled,x12_test_scaled,
#               x13_test_scaled, start , end , last):

def prep_data(x1_test,x2_test,x3_test,x4_test,x5_test,x6_test,x7_test,x8_test,
              x9_test,x10_test,x11_test,x12_test,x13_test, start , end , last):
    #prepare test data X
    dataset_test = hstack((x1_test,x2_test,x3_test,x4_test,x5_test,x6_test,
                          x7_test,x8_test,x9_test,x10_test,x11_test,x12_test,x13_test))
    print(dataset_test)
    dataset_test_X = dataset_test[start:end, :]
    test_X_new = dataset_test_X.reshape(1, dataset_test_X.shape[0] , dataset_test_X.shape[1])

  # predictions
    scaler1 = MinMaxScaler(feature_range=(0, 1))
    y_pred = model.predict(test_X_new)
    # print(y_pred)
    # y_pred_inv = scaler1.inverse_transform(y_pred)
    # print(y_pred_inv)
    y_pred_inv = y_pred.reshape(n_steps_out,1)
    # print(y_pred_inv)
    # y_pred_inv = y_pred_inv[:,0]
    
    return y_pred
    # return y_pred_inv 

In [ ]:
ans = []

In [ ]:
for i in range(0,16,1):
    print("i: ",i)
    start = i
    end = start + n_steps_in 
    last = end + n_steps_out 
    y_pred_inv1 = prep_data(AMB_TEMP_test,CO_test,NO_test,NO2_test,NOx_test,O3_test,PM10_test,
                            RAINFALL_test,RH_test,SO2_test,THC_test,cos_wind_test,sin_wind_test, start , end , last) 
    print(y_pred_inv1)

i:  0
[[15.          0.          0.66666667 ...  2.          1.33333333
   3.33333333]
 [14.66666667  0.          0.66666667 ...  2.          0.66666667
   3.33333333]
 [14.          0.          0.66666667 ...  2.          1.
   3.        ]
 ...
 [16.          0.          0.66666667 ...  1.          0.33333333
   3.33333333]
 [16.          0.          1.         ...  1.          0.33333333
   3.        ]
 [16.          0.          1.         ...  1.          0.33333333
   4.33333333]]
1/1 [==============================] - 0s 340ms/step
[[29.229431 29.151323 29.1666   29.12648  29.179224 29.186575 29.143433
  29.212612]]
i:  1
[[15.          0.          0.66666667 ...  2.          1.33333333
   3.33333333]
 [14.66666667  0.          0.66666667 ...  2.          0.66666667
   3.33333333]
 [14.          0.          0.66666667 ...  2.          1.
   3.        ]
 ...
 [16.          0.          0.66666667 ...  1.          0.33333333
   3.33333333]
 [16.          0.          1.         ...  1

In [ ]:
for i in range(0,8760,1):
    print("i: ",i)
    start = i
    end = start + n_steps_in 
    last = end + n_steps_out 
    y_pred_inv = prep_data(AMB_TEMP_test,CO_test,NO_test,NO2_test,NOx_test,O3_test,PM10_test,
                            RAINFALL_test,RH_test,SO2_test,THC_test,cos_wind_test,sin_wind_test, start , end , last) 
    ans.append(y_pred_inv)

串流輸出內容已截斷至最後 5000 行。
   3.33333333]
 [16.          0.          1.         ...  1.          0.33333333
   3.        ]
 [16.          0.          1.         ...  1.          0.33333333
   4.33333333]]
1/1 [==============================] - 0s 25ms/step
i:  6441
[[15.          0.          0.66666667 ...  2.          1.33333333
   3.33333333]
 [14.66666667  0.          0.66666667 ...  2.          0.66666667
   3.33333333]
 [14.          0.          0.66666667 ...  2.          1.
   3.        ]
 ...
 [16.          0.          0.66666667 ...  1.          0.33333333
   3.33333333]
 [16.          0.          1.         ...  1.          0.33333333
   3.        ]
 [16.          0.          1.         ...  1.          0.33333333
   4.33333333]]
1/1 [==============================] - 0s 26ms/step
i:  6442
[[15.          0.          0.66666667 ...  2.          1.33333333
   3.33333333]
 [14.66666667  0.          0.66666667 ...  2.          0.66666667
   3.33333333]
 [14.          0.          0.6666

KeyboardInterrupt: ignored

In [ ]:
# AMB_TEMP_test_scaled,CO_test_scaled,NO_test_scaled,NO2_test_scaled,NOx_test_scaled,O3_test_scaled,PM10_test_scaled,RAINFALL_test_scaled,RH_test_scaled,SO2_test_scaled,THC_test_scaled,cos_wind_test_scaled,sin_wind_test_scaled

In [ ]:
ans

[array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
         24.891642, 24.18502 ]], dtype=float32),
 array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
         24.891642, 24.18502 ]], dtype=float32),
 array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
         24.891642, 24.18502 ]], dtype=float32),
 array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
         24.891642, 24.18502 ]], dtype=float32),
 array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
         24.891642, 24.18502 ]], dtype=float32),
 array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
         24.891642, 24.18502 ]], dtype=float32),
 array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
         24.891642, 24.18502 ]], dtype=float32),
 array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
         24.891642, 24.18502 ]], dtype=float32),
 array([

In [ ]:
ans[0]

array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
        24.891642, 24.18502 ]], dtype=float32)

In [ ]:
len(ans)

8760

In [ ]:
q = ans[0:8]
print(len(q))

8


In [ ]:
k = ans[8:8752]

In [ ]:
len(k)

8744

In [ ]:
k[0]

array([[24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
        24.891642, 24.18502 ]], dtype=float32)

In [ ]:
k[0][0]

array([24.993473, 24.851242, 25.010874, 23.608355, 24.820005, 23.675732,
       24.891642, 24.18502 ], dtype=float32)

In [ ]:
k[0][0][0]

24.993473

# output


In [ ]:
# create an Empty DataFrame object
ans_df = pd.DataFrame(index=range(len(k)),columns=range(8))
  
print(ans_df )

        0    1    2    3    4    5    6    7
0     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...   ...  ...  ...  ...  ...  ...  ...  ...
8739  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8740  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8741  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8742  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
8743  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[8744 rows x 8 columns]


In [ ]:
for i in range(len(k)):
  for j in range(8):
    ans_df.iloc[i,j] = k[i][0][j]



In [ ]:
ans_df

In [ ]:
import os
ans_df.rename(columns = {0:'PM2.5-1'}, inplace = True)
ans_df.rename(columns = {1:'PM2.5-2'}, inplace = True)
ans_df.rename(columns = {2:'PM2.5-3'}, inplace = True)
ans_df.rename(columns = {3:'PM2.5-4'}, inplace = True)
ans_df.rename(columns = {4:'PM2.5-5'}, inplace = True)
ans_df.rename(columns = {5:'PM2.5-6'}, inplace = True)
ans_df.rename(columns = {6:'PM2.5-7'}, inplace = True)
ans_df.rename(columns = {7:'PM2.5-8'}, inplace = True)
ans_df.to_csv(os.path.join('/content/drive/MyDrive/code/python/projects/ADL/ADL_(IM5062)/111ntu-homework3','ans1_4.csv')) #save to file

In [ ]:
df3 = pd.read_csv('/content/drive/MyDrive/code/python/projects/ADL/ADL_(IM5062)/111ntu-homework3/ans1_4.csv')

In [ ]:
df3 

In [ ]:
df3.rename(columns = {'Unnamed: 0':'INDEX'}, inplace = True)
df3['INDEX'] = df3['INDEX']+1

In [ ]:
df3.to_csv(os.path.join('/content/drive/MyDrive/code/python/projects/ADL/ADL_(IM5062)/111ntu-homework3','ans1_4.csv'),index=False) #save to file

In [ ]:
FILE = 'hw3_1_4.pt'

In [ ]:
torch.save(model, FILE)